export type HardwareProduct = {
  slug: string;
  number: string;
  title: string;
  shortTitle: string;
  category: string;
  series: string;
  description: string;
  overview: string;
  highlights: string[];
  image: string;
};

export const productCategories = [
  'Smart switches',
  'Touch panels',
  'Magnetic+ glass',
  'IoT fans',
  'Kitchen appliances',
  'Pump controllers',
  'e-Label displays',
  'Power and connectivity',
] as const;

export const hardwareProducts: HardwareProduct[] = [
  {
    slug: 'lpf-1-switch',
    number: '01',
    title: 'LPF 1 Switch (16A Relay)',
    shortTitle: 'LPF 1',
    category: 'Smart switches',
    series: 'LPF',
    description: 'A single-gang LPF smart switch with a 16A relay for everyday lighting and appliance control.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/lpf-1-switch.jpg',
  },
  {
    slug: 'lpf-2-switch',
    number: '02',
    title: 'LPF 2 Switch (16A Relay)',
    shortTitle: 'LPF 2',
    category: 'Smart switches',
    series: 'LPF',
    description: 'A two-gang LPF smart switch with 16A relays for controlling two loads from one plate.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/lpf-2-switch.jpg',
  },
  {
    slug: 'nexa-1-switch',
    number: '03',
    title: 'NEXA 1 Switch (10A Relay)',
    shortTitle: 'NEXA 1',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A compact NEXA one-gang switch with a 10A relay for connected lighting circuits.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-1-switch.png',
  },
  {
    slug: 'nexa-2-switch',
    number: '04',
    title: 'NEXA 2 Switch (10A Relay)',
    shortTitle: 'NEXA 2',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A NEXA two-gang switch with 10A relays for paired lighting or mixed room loads.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-2-switch.png',
  },
  {
    slug: 'nexa-5-switch',
    number: '05',
    title: 'NEXA 5 Switch (10A Relay)',
    shortTitle: 'NEXA 5',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A five-gang NEXA switchboard with 10A relays for multi-point room control.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-5-switch.png',
  },
  {
    slug: 'nexa-1-switch-1-fan',
    number: '06',
    title: 'NEXA 1 Switch 1 Fan (10A Relay)',
    shortTitle: 'NEXA 1+Fan',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A NEXA plate combining one switch and one fan control on 10A relays.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-1-switch-1-fan.png',
  },
  {
    slug: 'nexa-hd-switch-25a',
    number: '07',
    title: 'NEXA HD Switch 25A',
    shortTitle: 'NEXA HD 25A',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A heavy-duty NEXA 25A switch with power monitoring for high-load circuits.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-hd-switch-25a.png',
  },
  {
    slug: 'nexa-2-switch-1-fan',
    number: '08',
    title: 'NEXA 2 Switch 1 Fan (10A Relay)',
    shortTitle: 'NEXA 2+Fan',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A NEXA combination plate with two switches and one fan control.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-2-switch-1-fan.png',
  },
  {
    slug: 'nexa-4-switch-1-fan',
    number: '09',
    title: 'NEXA 4 Switch 1 Fan (10A Relay)',
    shortTitle: 'NEXA 4+Fan',
    category: 'Smart switches',
    series: 'NEXA',
    description: 'A NEXA combination plate with four switches and one fan control for larger rooms.',
    overview: 'Karat Infinity smart switches bring everyday lighting and appliance circuits into a connected plate. Each model is specified by gang count and relay rating so installers can match the load, while the same family language stays consistent from a single switch to a full room plate.',
    highlights: ['Relay-based load control', 'Fits standard modular plates', 'Built for connected home and workspace circuits', 'Pairs with the Karat Infinity ecosystem'],
    image: '/products/nexa-4-switch-1-fan.png',
  },
  {
    slug: 'hd-touch-vpro',
    number: '10',
    title: 'HD Touch VPro (25A Relay and RGB LED)',
    shortTitle: 'HD Touch VPro',
    category: 'Touch panels',
    series: 'VPro',
    description: 'A high-duty 25A VPro touch panel with RGB LED feedback for connected high-load switching.',
    overview: 'VPro and RPro touch panels replace conventional rockers with a glass control surface. Relay ratings and RGB LED feedback are part of the product, so high-load circuits and multi-gang rooms can still feel like one control language.',
    highlights: ['Capacitive glass touch control', 'RGB LED status feedback', 'Relay switching for lighting and fans', 'Designed for premium connected interiors'],
    image: '/products/hd-touch-vpro.jpg',
  },
  {
    slug: '2-touch-vpro',
    number: '11',
    title: '2 Touch VPro (10A Relay and RGB LED)',
    shortTitle: '2 Touch VPro',
    category: 'Touch panels',
    series: 'VPro',
    description: 'A two-gang VPro glass touch panel with 10A relays and RGB LED indication.',
    overview: 'VPro and RPro touch panels replace conventional rockers with a glass control surface. Relay ratings and RGB LED feedback are part of the product, so high-load circuits and multi-gang rooms can still feel like one control language.',
    highlights: ['Capacitive glass touch control', 'RGB LED status feedback', 'Relay switching for lighting and fans', 'Designed for premium connected interiors'],
    image: '/products/2-touch-vpro.jpg',
  },
  {
    slug: 'fan-dimmer-touch-vpro',
    number: '12',
    title: 'Fan Dimmer Touch VPro (10A Relay and RGB LED)',
    shortTitle: 'Fan Dimmer VPro',
    category: 'Touch panels',
    series: 'VPro',
    description: 'A VPro touch dimmer for fan speed control with 10A relay switching and RGB LED feedback.',
    overview: 'VPro and RPro touch panels replace conventional rockers with a glass control surface. Relay ratings and RGB LED feedback are part of the product, so high-load circuits and multi-gang rooms can still feel like one control language.',
    highlights: ['Capacitive glass touch control', 'RGB LED status feedback', 'Relay switching for lighting and fans', 'Designed for premium connected interiors'],
    image: '/products/fan-dimmer-touch-vpro.jpeg',
  },
  {
    slug: '4-touch-rpro',
    number: '13',
    title: '4 Touch RPro (10A Relay and RGB LED)',
    shortTitle: '4 Touch RPro',
    category: 'Touch panels',
    series: 'RPro',
    description: 'A four-gang RPro touch panel with 10A relays and RGB LED indication.',
    overview: 'VPro and RPro touch panels replace conventional rockers with a glass control surface. Relay ratings and RGB LED feedback are part of the product, so high-load circuits and multi-gang rooms can still feel like one control language.',
    highlights: ['Capacitive glass touch control', 'RGB LED status feedback', 'Relay switching for lighting and fans', 'Designed for premium connected interiors'],
    image: '/products/4-touch-rpro.jpg',
  },
  {
    slug: 'magnetic-glass-touch-2-switch',
    number: '14',
    title: 'Magnetic+ Glass Touch 2 Switch (2M/3M)',
    shortTitle: 'Magnetic+ 2 Switch',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A two-switch Magnetic+ glass touch plate in 2M/3M modular sizes.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-2-switch.jpg',
  },
  {
    slug: 'magnetic-glass-touch-4-switch',
    number: '15',
    title: 'Magnetic+ Glass Touch 4 Switch (2M/3M)',
    shortTitle: 'Magnetic+ 4 Switch',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A four-switch Magnetic+ glass touch plate in 2M/3M modular sizes.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-4-switch.jpg',
  },
  {
    slug: 'magnetic-glass-touch-fan-switch',
    number: '16',
    title: 'Magnetic+ Glass Touch Fan Switch (2M/3M)',
    shortTitle: 'Magnetic+ Fan',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A Magnetic+ glass touch fan controller in 2M/3M modular sizes.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-fan-switch.jpg',
  },
  {
    slug: 'magnetic-glass-touch-4-switch-1-fan',
    number: '17',
    title: 'Magnetic+ Glass Touch 4 Switch 1 Fan (4M)',
    shortTitle: 'Magnetic+ 4+Fan',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A 4M Magnetic+ plate with four switches and one fan control, including HD and 2-way options.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-4-switch-1-fan.jpg',
  },
  {
    slug: 'magnetic-glass-touch-8-switch-1-socket',
    number: '18',
    title: 'Magnetic+ Glass Touch 8 Switch 1 Socket (6M)',
    shortTitle: 'Magnetic+ 8+Socket',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A 6M Magnetic+ plate with eight switches and one socket, including HD and 2-way options.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-8-switch-1-socket.jpg',
  },
  {
    slug: 'magnetic-glass-touch-4-switch-1-fan-1-socket',
    number: '19',
    title: 'Magnetic+ Glass Touch 4 Switch 1 Fan 1 Socket (6M)',
    shortTitle: 'Magnetic+ 4 Combo',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A 6M Magnetic+ combination plate for switches, fan control and a socket.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-4-switch-1-fan-1-socket.jpg',
  },
  {
    slug: 'magnetic-glass-touch-8-switch-1-fan',
    number: '20',
    title: 'Magnetic+ Glass Touch 8 Switch 1 Fan (8M)',
    shortTitle: 'Magnetic+ 8+Fan',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'An 8M Magnetic+ plate with eight switches and one fan control.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-8-switch-1-fan.jpg',
  },
  {
    slug: 'magnetic-glass-touch-16-switch-2-fan',
    number: '21',
    title: 'Magnetic+ Glass Touch 16 Switch 2 Fan (12M)',
    shortTitle: 'Magnetic+ 16+2 Fan',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A 12M Magnetic+ plate with sixteen switches and two fan controls.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-16-switch-2-fan.jpg',
  },
  {
    slug: 'magnetic-glass-touch-12-switch-1-fan-2-socket',
    number: '22',
    title: 'Magnetic+ Glass Touch 12 Switch 1 Fan 2 Socket (12M)',
    shortTitle: 'Magnetic+ 12 Combo',
    category: 'Magnetic+ glass',
    series: 'Magnetic+',
    description: 'A 12M Magnetic+ combination plate with twelve switches, one fan control and two sockets.',
    overview: 'Magnetic+ glass touch plates combine switches, fan control and sockets in modular sizes from 2M to 12M. HD and 2-way options are called out on the combination models so larger rooms can be specified from a single family.',
    highlights: ['Magnetic+ glass touch finish', 'Modular 2M to 12M plate sizes', 'HD and 2-way switching options', 'Combines switches, fans and sockets on one plate'],
    image: '/products/magnetic-glass-touch-12-switch-1-fan-2-socket.jpg',
  },
  {
    slug: 'rockair-5blade-bldc-iot-fan',
    number: '23',
    title: 'Rockair 5-Blade BLDC IoT Fan',
    shortTitle: 'Rockair',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A five-blade Rockair BLDC ceiling fan with IoT control for quieter, connected airflow.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/rockair-5blade-bldc-iot-fan.jpg',
  },
  {
    slug: 'atom-3blade-bldc-iot-fan',
    number: '24',
    title: 'Atom 3-Blade BLDC IoT Fan',
    shortTitle: 'Atom',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A three-blade Atom BLDC ceiling fan with IoT control for compact rooms.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/atom-3blade-bldc-iot-fan.jpg',
  },
  {
    slug: 'glostar-3blade-bldc-iot-fan',
    number: '25',
    title: 'GloStar 3-Blade BLDC IoT Fan',
    shortTitle: 'GloStar',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A three-blade GloStar BLDC ceiling fan with IoT control and a decorative profile.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/glostar-3blade-bldc-iot-fan.jpg',
  },
  {
    slug: 'sportage-blade-bldc-iot-fan',
    number: '26',
    title: 'Sportage Blade BLDC IoT Fan',
    shortTitle: 'Sportage',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A Sportage-blade BLDC ceiling fan with IoT control for connected living spaces.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/sportage-blade-bldc-iot-fan.jpg',
  },
  {
    slug: 'arval-3blade-bldc-iot-fan',
    number: '27',
    title: 'Arval 3-Blade BLDC IoT Fan',
    shortTitle: 'Arval',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A three-blade Arval BLDC ceiling fan with IoT control.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/arval-3blade-bldc-iot-fan.jpg',
  },
  {
    slug: 'iot-multi-cooker',
    number: '28',
    title: 'IoT Multi Cooker',
    shortTitle: 'IoT Cooker',
    category: 'Kitchen appliances',
    series: 'IoT appliances',
    description: 'A connected multi cooker for scheduled, remote and sensor-aware cooking.',
    overview: 'The IoT multi cooker extends Karat Infinity beyond switches and fans into the kitchen. It is specified as a connected appliance so cooking can follow the same remote and scheduled control model as the rest of the product family.',
    highlights: ['IoT scheduling and remote status', 'Built for everyday kitchen workflows', 'Connects physical cooking to digital control', 'Part of the Karat Infinity connected-product line'],
    image: '/products/iot-multi-cooker.jpg',
  },
  {
    slug: '1phase-pump-controller-iot',
    number: '29',
    title: '1-Phase Pump Controller with IoT',
    shortTitle: '1-Phase IoT Pump',
    category: 'Pump controllers',
    series: 'Pump control',
    description: 'A single-phase pump controller with IoT monitoring and remote operation.',
    overview: 'Pump controllers cover 1-phase IoT, 3-phase IoT and 3-phase GSM models. They are field products: start, stop and status for agricultural or utility pumps, with connectivity chosen for the site.',
    highlights: ['Single or three-phase pump control', 'IoT or GSM connectivity options', 'Remote start, stop and status visibility', 'Built for agricultural and utility installations'],
    image: '/products/1phase-pump-controller-iot.png',
  },
  {
    slug: '3phase-pump-controller-iot',
    number: '30',
    title: '3-Phase Pump Controller with IoT',
    shortTitle: '3-Phase IoT Pump',
    category: 'Pump controllers',
    series: 'Pump control',
    description: 'A three-phase pump controller with IoT monitoring for agricultural and utility pumps.',
    overview: 'Pump controllers cover 1-phase IoT, 3-phase IoT and 3-phase GSM models. They are field products: start, stop and status for agricultural or utility pumps, with connectivity chosen for the site.',
    highlights: ['Single or three-phase pump control', 'IoT or GSM connectivity options', 'Remote start, stop and status visibility', 'Built for agricultural and utility installations'],
    image: '/products/3phase-pump-controller-iot.png',
  },
  {
    slug: '3phase-pump-controller-gsm',
    number: '31',
    title: '3-Phase Pump Controller with GSM',
    shortTitle: '3-Phase GSM Pump',
    category: 'Pump controllers',
    series: 'Pump control',
    description: 'A three-phase pump controller with GSM connectivity where internet is limited.',
    overview: 'Pump controllers cover 1-phase IoT, 3-phase IoT and 3-phase GSM models. They are field products: start, stop and status for agricultural or utility pumps, with connectivity chosen for the site.',
    highlights: ['Single or three-phase pump control', 'IoT or GSM connectivity options', 'Remote start, stop and status visibility', 'Built for agricultural and utility installations'],
    image: '/products/3phase-pump-controller-gsm.png',
  },
  {
    slug: 'bldc-ceiling-fan-iot',
    number: '32',
    title: 'BLDC Ceiling Fan with IoT',
    shortTitle: 'BLDC IoT Fan',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A connected BLDC ceiling fan designed for efficient, app-ready room airflow.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/bldc-ceiling-fan-iot.png',
  },
  {
    slug: 'bldc-ceiling-fan-iot-ii',
    number: '33',
    title: 'BLDC Ceiling Fan with IoT — Variant',
    shortTitle: 'BLDC IoT Fan II',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A second BLDC IoT ceiling fan variant from the Karat Infinity product list.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/bldc-ceiling-fan-iot-ii.png',
  },
  {
    slug: 'bldc-ceiling-fan-led-wooden',
    number: '34',
    title: 'BLDC Ceiling Fan with LED and Wooden Blades',
    shortTitle: 'Wooden LED Fan',
    category: 'IoT fans',
    series: 'BLDC fans',
    description: 'A BLDC ceiling fan with wooden blades and integrated LED lighting.',
    overview: 'The BLDC IoT fan range covers named models such as Rockair, Atom, GloStar, Sportage and Arval, plus ceiling-fan variants with LED and wooden blades. Each fan is a connected product first — efficient airflow with a path into the Karat Infinity ecosystem.',
    highlights: ['BLDC motor efficiency', 'IoT-ready speed and schedule control', 'Designed for connected living spaces', 'Works with the wider Karat Infinity product family'],
    image: '/products/bldc-ceiling-fan-led-wooden.png',
  },
  {
    slug: 'jewellery-elabel-1inch',
    number: '35',
    title: 'Jewellery e-Label Display 1 inch',
    shortTitle: 'e-Label 1 in',
    category: 'e-Label displays',
    series: 'e-Label',
    description: 'A 1-inch electronic label display for jewellery pricing and product identity.',
    overview: 'e-Label displays bring product information onto the counter and the shelf. Jewellery sizes start at 1 inch; shop labels go up to 4.1 inch, so pricing and identity can be updated digitally instead of reprinting paper tags.',
    highlights: ['Electronic product labelling', 'Sizes for jewellery and retail shelves', 'Update pricing without printed labels', 'Connects physical products to digital information'],
    image: '/products/jewellery-elabel-1inch.png',
  },
  {
    slug: 'jewellery-elabel-1-5inch',
    number: '36',
    title: 'Jewellery e-Label Display 1.5 inch',
    shortTitle: 'e-Label 1.5 in',
    category: 'e-Label displays',
    series: 'e-Label',
    description: 'A 1.5-inch electronic label display for jewellery counters.',
    overview: 'e-Label displays bring product information onto the counter and the shelf. Jewellery sizes start at 1 inch; shop labels go up to 4.1 inch, so pricing and identity can be updated digitally instead of reprinting paper tags.',
    highlights: ['Electronic product labelling', 'Sizes for jewellery and retail shelves', 'Update pricing without printed labels', 'Connects physical products to digital information'],
    image: '/products/jewellery-elabel-1-5inch.png',
  },
  {
    slug: 'jewellery-elabel-2-1inch',
    number: '37',
    title: 'Jewellery e-Label Display 2.1 inch',
    shortTitle: 'e-Label 2.1 in',
    category: 'e-Label displays',
    series: 'e-Label',
    description: 'A 2.1-inch electronic label display for jewellery product information.',
    overview: 'e-Label displays bring product information onto the counter and the shelf. Jewellery sizes start at 1 inch; shop labels go up to 4.1 inch, so pricing and identity can be updated digitally instead of reprinting paper tags.',
    highlights: ['Electronic product labelling', 'Sizes for jewellery and retail shelves', 'Update pricing without printed labels', 'Connects physical products to digital information'],
    image: '/products/jewellery-elabel-2-1inch.png',
  },
  {
    slug: 'elabel-display-2-1inch-shops',
    number: '38',
    title: 'e-Label Display 2.1 inch for Shops',
    shortTitle: 'Shop e-Label 2.1 in',
    category: 'e-Label displays',
    series: 'e-Label',
    description: 'A 2.1-inch electronic shelf label for retail pricing and product details.',
    overview: 'e-Label displays bring product information onto the counter and the shelf. Jewellery sizes start at 1 inch; shop labels go up to 4.1 inch, so pricing and identity can be updated digitally instead of reprinting paper tags.',
    highlights: ['Electronic product labelling', 'Sizes for jewellery and retail shelves', 'Update pricing without printed labels', 'Connects physical products to digital information'],
    image: '/products/elabel-display-2-1inch-shops.png',
  },
  {
    slug: 'elabel-display-2-9inch-shops',
    number: '39',
    title: 'e-Label Display 2.9 inch for Shops',
    shortTitle: 'Shop e-Label 2.9 in',
    category: 'e-Label displays',
    series: 'e-Label',
    description: 'A 2.9-inch electronic shelf label for shop aisles and counter displays.',
    overview: 'e-Label displays bring product information onto the counter and the shelf. Jewellery sizes start at 1 inch; shop labels go up to 4.1 inch, so pricing and identity can be updated digitally instead of reprinting paper tags.',
    highlights: ['Electronic product labelling', 'Sizes for jewellery and retail shelves', 'Update pricing without printed labels', 'Connects physical products to digital information'],
    image: '/products/elabel-display-2-9inch-shops.png',
  },
  {
    slug: 'elabel-display-4-1inch-shops',
    number: '40',
    title: 'e-Label Display 4.1 inch for Shops',
    shortTitle: 'Shop e-Label 4.1 in',
    category: 'e-Label displays',
    series: 'e-Label',
    description: 'A 4.1-inch electronic shelf label for larger retail product information.',
    overview: 'e-Label displays bring product information onto the counter and the shelf. Jewellery sizes start at 1 inch; shop labels go up to 4.1 inch, so pricing and identity can be updated digitally instead of reprinting paper tags.',
    highlights: ['Electronic product labelling', 'Sizes for jewellery and retail shelves', 'Update pricing without printed labels', 'Connects physical products to digital information'],
    image: '/products/elabel-display-4-1inch-shops.png',
  },
  {
    slug: 'smart-plug-iot',
    number: '41',
    title: 'Smart Plug with IoT',
    shortTitle: 'Smart Plug',
    category: 'Power and connectivity',
    series: 'IoT power',
    description: 'A connected smart plug for scheduling, remote switching and appliance monitoring.',
    overview: 'The smart plug and busbar system sit at the edge of the electrical installation. One adds IoT control at a socket; the other organises distribution — both belong in the same Karat Infinity product catalogue as the switches and fans.',
    highlights: ['Adds connected control at the socket or distribution layer', 'Designed for installations alongside Karat Infinity switches', 'IoT-ready where the product supports it', 'Completes the on-site electrical product family'],
    image: '/products/smart-plug-iot.jpeg',
  },
  {
    slug: 'busbar-system',
    number: '42',
    title: 'Busbar System',
    shortTitle: 'Busbar',
    category: 'Power and connectivity',
    series: 'Power distribution',
    description: 'A busbar system for organised, compact electrical distribution in connected installations.',
    overview: 'The smart plug and busbar system sit at the edge of the electrical installation. One adds IoT control at a socket; the other organises distribution — both belong in the same Karat Infinity product catalogue as the switches and fans.',
    highlights: ['Adds connected control at the socket or distribution layer', 'Designed for installations alongside Karat Infinity switches', 'IoT-ready where the product supports it', 'Completes the on-site electrical product family'],
    image: '/products/busbar-system.png',
  },
];

export function getHardwareProduct(slug: string) {
  return hardwareProducts.find((product) => product.slug === slug);
}

export const featuredProductSlugs = [
  'lpf-1-switch',
  'nexa-hd-switch-25a',
  'magnetic-glass-touch-4-switch',
  'rockair-5blade-bldc-iot-fan',
  'jewellery-elabel-2-1inch',
  'smart-plug-iot',
] as const;

export const featuredProducts = featuredProductSlugs
  .map((slug) => hardwareProducts.find((product) => product.slug === slug))
  .filter((product): product is HardwareProduct => Boolean(product));
